version: '3.5'

services:
  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passworddificilLucasasds
      POSTGRES_DB: db-lavroura
    container_name: db-postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db-postgres
    volumes:
      - ./src:/app/src